[package]
name = "find_words"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "Weekly challenge 315 task 1 - find words containing a character"
authors = ["Peter Pentchev <roam@ringlet.net>"]
license = "BSD-2-Clause"
