#!/bin/bash

[ $1 ] || { echo "Usage: $0 <challenge number>" >&2; exit 2; }

challenge="$1"

set -v

git update-index --refresh -q >/dev/null
if ! git diff-index --quiet HEAD --; then
    git stash
    stashed=1
fi

set -e
git checkout dev
git pull

git checkout master
git pull

git fetch upstream
git merge --ff-only upstream/master

if git checkout muthm-$challenge; then
    update=" - Update"
else
    git checkout -b muthm-$challenge
    update=""
fi

dir="challenge-$challenge/matthias-muth"
git checkout dev -- "$dir"

echo "Activating testing section prepared for publishing"
perl -i~ -g -n -E '
    /^# version for publishing/mi or do {
        warn "no '\''publishing'\'' template in '\''$ARGV'\''\n";
        print;
        next;
    };
    s<^use lib .*?\n^use MultiTest.*?\n>
        <use Test2::V0 qw( -no_srand );\n>ms;
    s<^run.*?\n.*Version for publishing.*use Test2::V.*?\n><>msi;
    print
' "$dir"/perl/ch-[12].pl
git add -u

git commit -m "Challenge $challenge Task 1 and 2 solutions in Perl by Matthias Muth$update"
git push --set-upstream origin muthm-$challenge

git push --all
git push --tags

git checkout dev

if [ "$stashed" ]; then
    git stash pop
    git status -uno
fi
