#!/bin/bash

[ $1 ] || { echo "Usage: $0 <challenge number>" >&2; exit 2; }

challenge="$1"

set -v

git update-index --refresh -q >/dev/null
if ! git diff-index --quiet HEAD --; then
    git stash
    stashed=1
fi

set -e
git checkout dev
git pull

git checkout master
git pull

git fetch upstream
git merge --ff-only upstream/master

git checkout muthm-$challenge \
    || git checkout -b muthm-$challenge
git checkout dev -- challenge-$challenge/matthias-muth
git commit -m "Challenge $challenge Task 1 and 2 solutions in Perl by Matthias Muth"
git push --set-upstream origin muthm-$challenge

git push --all
git push --tags

git checkout dev

if [ "$stashed" ]; then
    git stash pop
    git status -uno
fi
