#!/usr/bin/env perl
#
#	download_challenge [<options>] [<challenge> ...]
#		downloads the challenges given as parameters from the
#		Weekly Challenge website at https://theweeklychallenge.org,
#		and creates several files based on the information extracted
#		from the challenge. All files will be created in the
#		subdirectory
#		    challenge-<challenge>/<user>
#		(where <challenge> is the challenge number, and <user> is the
#		user name as specified in the status.toml confguration file).
#		These files will be created:
#		  * README-no-blog.md
#		  	(to be moved or copied to README.md in case no blog is
#		  	written for this week's challenge)
#		  * blog.txt
#		  * perl/README-<challenge>.md
#		  	(blog skeleton; to be moved up to ../README.md after
#		  	editing)
#		  * perl/ch-1.pl
#		  * perl/ch-1.pl
#		  * perl/challenge-<challenge>.
#		No files will be overwritten if they already exist, except the
#		'perl/challenge-<challenge>' file. This is because the
#		challenge text is not supposed to be changed locally, but it
#		might receive updates or corrections on the website.
#
#
#		If no parameters are given, the script checks whether there is
#		a new challenge, or an update to the current challenge.
#		Header and checksum information of the challenge main page and
#		the current challenge page are kept to avoid downloading and
#		updating files unnecessarily if nothing has changed.
#		If there is a change, an email containing the extracted
#		challenge text HTML is sent to a default list of recipients,
#		in addition to writing the above mentioned output files.
#		[TBC...]
#
#	Usage:
#	    download_challenge
#		Without parameters, executes these default tasks:
#		  * retrieve the task descriptions for the most recent weekly
#		    challenge from the Weekly Challenge website.
#	        If the challenge number or the task descriptions have changed:
#		  * write a text file 'challenge-<challenge>.txt' containing the
#		    task descriptions in the
#		    .../challenge-<challenge>/<user>/perl directory,
#		    if the task descriptions have changed,
#		    (where <user> is the challenge user name, as specified in
#		    the 'status.toml' file),
#		  * send the task descriptions as html email to a default list
#		    of recipients (specified in 'status.toml').
#		  * generate skeleton files for .../perl/ch-[12].pl based on
#		    the challenge task descriptions, if they do not yet exist.
#
#	    download_challenge <challenge> ...
#		When challenge numbers are explicitly given as command line
#		parameters, only these steps are done by default:
#		  * retrieve the task descriptions for the given challenges,
#		  * write the task text files if they have changed,
#		  * generate the code skeleton files if they do not yet exist.
#		No mail is sent unless the -mail <recipient> option is
#		given explicitly.
#
#	Options:	[WIP!]
#	    -input <html file> | -i <html file>
#	    	Read html from <html file> instead of retrieving it from the
#	    	Weekly Challenge web site.
#	    -nofiles | -nof
#	        Do not write any output files.
#	    -mail <recipient>
#		Send mail (or mails) to <recipient>.
#		The default list of recipients is not used if this option is
#		given.
#		This option can be used multiple times.
#	    -nomail | -nom
#		Do not send any default emails.
#

use v5.26;
use strict;
use warnings;
use feature 'signatures';
no warnings 'experimental::signatures';

use utf8;
binmode(STDOUT, ":utf8");
use open ':encoding(utf-8)';    # Sets the default encoding for handles opened in scope.

use Verbose;
use Dsay;

use Getopt::Long qw( :config no_ignore_case );
use TOML;
use Time::Piece;

use HTML::TreeBuilder::XPath;
use LWP::Simple;
use URI::Escape;

use File::Basename;
use File::Path qw( make_path );

use Digest::MD5 qw( md5_hex );
use Encode qw( encode_utf8 );
use Email::Stuffer;

use lib qw( . );
use TestExtractor;

sub error_exit { say STDERR $0 =~ s'^.*/''r, ": ", @_; exit 1 }
sub usage      { say STDERR "Usage!"; exit 2 }

GetOptions(
    "force|f!"   => sub { $options{FORCE} = $_[1] ? ++$options{FORCE} : 0 },
    "FORCE"      => sub { $options{FORCE} = 2 },
    "new"        => sub { $options{FORCE} = 3 },
    "check|n"    => \$options{DRY_RUN},
    "mail:s"     => sub { push $options{MAIL_TO}->@*, split /[,\s]\s*/, $_[1] },
    "nomail"     => sub { $options{MAIL_TO} = []; },	# Defined but empty.
    "nogit"      => \$options{NO_GIT},
    "input|i:s"  => \$options{INPUT_FILE},
    "files!"     => \$options{WRITE_FILES},
    "archive!"   => \$options{ARCHIVE},
    "quiet|q!"   => \$options{QUIET},
    "verbose|v!" => \$verbose,
    "help|?"     => \&usage,
) or do {
    say STDERR "    Use '$0 -help' for usage information.";
    exit 2;
};

# Read 'status.toml' and templates, keep them as global variables.
our $status   = read_toml( "status.toml" );
our $templates = read_toml( "templates.toml" );

# Defaults:
$options{FORCE} //= 0;
$options{WRITE_FILES} //= 1;

# We have two modes:
# - Update mode:
#   Marked by not having command line arguments, and no -input option.
#   dealing with the latest challenge only,
#   The challenge will be read from the challenge page,
#   the challenge html will be saved in the 'challenge-htmls' subdirectory,
#   and the checksum and page times written to status.toml.
#   Sending emails unless -nomail is given.
# - Re-extraction mode:
#   Marked by a challenge number as a command line argument, or a -input
#   option.
#   No checksum checking, no status.toml updates.
#   Not sending emails, unless -mail <recipient> options are given.

unless ( @ARGV ) {
    # We use the following option to decide whether to always send mails
    # or only when there was a change.
    # Also, for updates of the most recent challenge, we need to keep track of
    # the modification times and md5 checksums.
    # Also write an archive file for the challenge html if not told otherwise.
    # We do none of these by default if the challenge numbers are given
    # explicitly.
    $options{UPDATE} = 1;
    $options{ARCHIVE} //= 1;

    # Send mail to default recipients if no challenge arguments are given.
    $options{MAIL_TO} //= $status->{'mail-recipients'};
}

error_exit "cannot use both '-i <file>' and a challenge number argument"
    if @ARGV && $options{INPUT_FILE};

$debug{'OPTIONS'} and do {
    dsay ":options", pp_hash %options;
    exit 0;
};

# If input is from a file, the challenge number will be taken from that file.
my $challenge =
    $options{INPUT_FILE} ? undef
        : @ARGV ? shift
        : get_challenge_to_update();

process_challenge( $challenge )
    if $challenge || $options{INPUT_FILE};

# Update the status toml file.
write_toml( $status )
    if $options{UPDATE} && ! $options{DRY_RUN};

exit 0;

#
# Subroutine definitions:
#

sub process_challenge( $challenge ) {

    # Extract relevant HTML parts (page header and task descriptions)
    # from the challenge page.

    local $d_area = "html";
    my $page_html =
        $options{INPUT_FILE}
        ? do {
            vsay "using input file '$options{INPUT_FILE}'";
            do { local ( @ARGV, $/ ) = $options{INPUT_FILE}; <> };
        }
        : do {
            my ( $main_url, $challenge_path ) =
                @$status{ qw( main-url current-challenge-path ) };
            $challenge_path =~ s/\d+/$challenge/;
            vsay "downloading $main_url$challenge_path";
            get( $main_url . $challenge_path )
        }
        or error_exit "page html is empty, cannot continue";

    my ( $title, $page_title, $published_date, $tasks, $deadline ) =
        map {
            m'<title\b.*?>(.*?\d+)',
            m'<h1\b.*?>(.*?)</h1>'m,
            m'^\s*(Published .*)$'m,
            m'(<h2 id="TASK1">.*)\n+<p>.*?(Last date to submit.*?)</p>'s,
        } $page_html;

    unless ( $challenge ) {
        ( $challenge ) = $title =~ /(\d+)/;
        vsay "extracted challenge number '$challenge'";
    }

    %debug and do {
        local $d_area = "extract";
        dsay "title: ", pp $title;
        dsay "page_title: ", pp $page_title;
        dsay "published_date: ", pp $published_date;
        dsay "tasks: ",
            pp substr( $tasks, 0, 30 ) . " ... " . substr( $tasks, -20 );
        dsay "deadline ", pp $deadline;
    };

    # The tasks html will be used for checking whether the task descriptions
    # have changed, and then also for sending mails (or not).

    # Create the tasks html from the template,
    # copying in the extracted HTML parts.
    my $tasks_html = $templates->{'mail'}{'mail_html'};
    my %substitutions = (
        CHALLENGE   => $challenge,
        CSS         => "<style>\n" . $templates->{'mail'}{'mail_css'}
                        . "</style>",
        PUBLISHED   => $published_date,
        TASKS       => $tasks,
        DEADLINE    => $deadline,
    );
    $tasks_html =~ s/<$_>/$substitutions{$_}/g
        for keys %substitutions;
    %debug and dsay ":tasks_html", "tasks_html:\n", pp $tasks_html;
    spit_file( "mail.html", $tasks_html );

    error_exit "tasks html is empty, cannot continue"
        unless $tasks_html;

    # If we are running an update, check whether the challenge html has changed.
    my $md5 = md5_hex( encode_utf8( $tasks_html ) );
    my $html_has_changed = undef;
    if ( $options{UPDATE} ) {
        $html_has_changed = $md5 ne $status->{'current-challenge-html-md5'};
        if ( $html_has_changed ) {
            dsay "current md5: $status->{'current-challenge-html-md5'}";
            prot "Task description html has changed (md5:$md5)"
                unless ! $status->{'current-challenge-html-md5'};
            set_toml( $status, 'current-challenge-html-md5', $md5 );
        }
        else {
            vsay "Task description html is unchanged.";
            $options{ARCHIVE} = 0;
        }
    }
    else {
        vsay "Task description will be used unconditionally.";
    }

    # Send mails.
    # For updates, send mails only if the html text has changed.
    if ( ( ! $options{UPDATE} || $html_has_changed ) && $options{MAIL_TO} ) {
        for my $rcpt ( @{$options{MAIL_TO}} ) {
            if ( $options{DRY_RUN} ) {
                say "would send email to $rcpt"
		    unless $options{QUIET};
            }
            else {
                vsay "sending email to $rcpt";
                Email::Stuffer
                    ->from( 'muthm@muthnet.de' )
                    ->to( $rcpt )
                    ->subject( $title )
                    ->html_body( $tasks_html )
                    ->send_or_die;
                prot "Sent email to $rcpt"
                    unless $options{QUIET};
            }
        }
    }

    # Write files.
    if ( $options{WRITE_FILES} ) {
	# The README.md file is created by the maintainer of the 'master'
	# branch when the new challenge directories are created.
	# It is copied from the previous week's challenge.
	# In order to update it to the current week's skeleton, we need
	# to make sure that the repository was updated and the file checked out
	# first.

        my $target_dir = "../challenge-$challenge/$status->{user}";
	my $readme_file = "$target_dir/README.md";

	my $dry_run_readme_msg = "";
	if ( ! -f $readme_file ) {
	    unless ( $options{DRY_RUN} || $options{NO_GIT} ) {
		system "./update_git.pl" . ( $verbose ? " -v" : " -q" );
	    }
	    else {
		$dry_run_readme_msg = " or '.../README.md'";
	    }

	    # If the file exists now, it is the previous week's version.
	    # We remove it to make space for this week's skeleton.
	    if ( -f $readme_file ) {
		unlink $readme_file;
	    }
	    else {
		# If it doesn't exist, it may need to be checked out from Git
		# manually. We keep that space clear and use another name.
		$readme_file = "$target_dir/README-$challenge.md";
	    }
	}

	# Extract a pure text version of the challenge description.
        my $tree = HTML::TreeBuilder::XPath->new( ignore_unknown => 0 );
        $tree->parse_content( $tasks_html )
            or error_exit "could not parse html data";

        # Extract nodes containing the title and the date,
        # followed by two <br> to create empty lines,
        # followed by everything inside the <div class="post-content"> block,
        # individually.
        my @nodes = $tree->findnodes( '//article/*' );
        error_exit "could not extract tasks text from tasks html"
            unless @nodes;

        # Extract the text from the nodes.
        # Ignore <hr> to avoid empty lines where they are not needed.
        # Add an extra empty line before 'Example 1'.
        # Reduce multiple empty lines to one within <pre> text
        # (example descriptions).
        # Add an extra empty line after <h5> ('submitted by').
        my $challenge_text = join "",
            "$page_title\n",
            "$published_date\n",
            "\n",
            map {
                ( $_->as_text =~ /^Example 1/ ? "\n" : "" )
                . ( $_->{_tag} =~ /^pre/
                    ?  $_->as_text =~ s/^\s*$//gmr
                    : $_->as_text )
                . "\n"
                . ( $_->{_tag} =~ /^h5/ ? "\n" : "" )
            } grep $_->{_tag} ne "hr", @nodes;
        %debug and dsay ":html", "challenge_text:\n", $challenge_text;

        # Generate the code skeletons and json data.
        my @tasks = ( undef );  # Task numbers are 1-based.
        for my $task_text (  $challenge_text =~ /(^Task 1.*)(^Task 2.*)/ms ) {
            my $tests = [ TestExtractor::extract_tests( $task_text ) ];
            %debug and dsay "extracted tests: ", pp( $tests );
            my $code = generate_code( $challenge, $task_text,
                    $templates->{code}{'ch-N_pl'}, $tests );
            my $json = generate_code( $challenge, $task_text,
                    $templates->{json}{'json'}, $tests );
            push @tasks, {
                text => $task_text,
                tests => $tests,
                code => $code,
                json => $json,
            };
        }

        # Generate the README.md skeleton.
        my $readme_text = generate_readme_md( $challenge, $challenge_text );

        # Generate README-no-blog.md
        my $readme_no_blog_text = $templates->{readme}{readme_no_blog};
        $readme_no_blog_text =~ s/<CHALLENGE>/$challenge/g;

        # Generate blog.txt
        my $blog_text = $templates->{readme}{blog_txt};
        $blog_text =~ s/<CHALLENGE>/$challenge/g;

        # Write out all files.
        #  - a local archive copy of the html if the html has changed,
        #  - the task descriptions text file,
        #  - the code files, not overwriting them if they already exist.

        my $archive_dir = "./challenge_htmls/$challenge";
        my $archive_file =
            $status->{'current-challenge-last-modified'} . "_$md5";
        $archive_file =~ s/[-:]//g;

        my @file_operations =
            ( ! $options{UPDATE} || $html_has_changed || $options{FORCE} )
            ? (
                $options{UPDATE} && $options{ARCHIVE}
                    ? [ "$archive_dir/$archive_file", $page_html ]
                    : (),
                [ "$target_dir/README-no-blog.md",
                    $readme_no_blog_text, 'DO_NOT_OVERWRITE' ],
                [ "$target_dir/blog.txt",
                    $blog_text, 'DO_NOT_OVERWRITE' ],
                [ $readme_file,
                    $readme_text, 'DO_NOT_OVERWRITE', $dry_run_readme_msg ],
                [ "$target_dir/perl/challenge-$challenge.txt",
                    $challenge_text ],
                ( map [ "$target_dir/perl/ch-$_.pl",
                        $tasks[$_]{code}, 'DO_NOT_OVERWRITE' ], 1..2 ),
                ( map [ "$target_dir/perl/ch-$_.json",
                        $tasks[$_]{json} ], 1..2 ),
            ) : ();

        for ( @file_operations ) {
            my ( $file, $contents, $do_not_overwrite, $add_msg ) =
		@$_;
            my %verb_forms =
                $options{DRY_RUN}
                ?  ( write => "write", overwrite => "overwrite" )
                :  ( write => "writing", overwrite => "overwriting" );
            my $msg =
                ( $options{DRY_RUN} ? "would " : "" )
                . ( ( -f $file && $do_not_overwrite && $options{FORCE} < 2 )
                    ? "not " : "" )
                . ( -f $file
                    ? ( ( ( $do_not_overwrite && $options{FORCE} >= 2 )
                            ? "forcefully " : "" )
                        . $verb_forms{"overwrite"} )
                    : $verb_forms{"write"} )
                . " '$file'"
		. ( $add_msg || "" );
            vsay $msg;
            unless ( $options{DRY_RUN} ) {
                make_path dirname( $file );
                spit_file( $file, $contents )
                    unless -f $file && $do_not_overwrite && $options{FORCE} < 2;
                chmod 0755, $file
                    if $file =~ /.pl$/;
            }
        }
    }
}

sub retrieve_challenge_link( $base_url, $pattern ) {
    my $tree = HTML::TreeBuilder::XPath->new_from_url( $base_url )
        or error_exit "could not retrieve data from $base_url";
    my $xpath  = "//\@href[.=~/$pattern/";
    my $link = $tree->findvalue( $xpath )
        or error_exit "did not find xpath '$xpath' in data";
    return $link;
}

sub get_challenge_to_update {
    local $d_area = "check";

    # Return the current challenge number if there needs to be an update,
    # or the new challenge number if it has changed.
    # Otherwise return nothing.

    my ( $challenge ) = $status->{'current-challenge-path'} =~ /(\d+)/;

    # Step 1:
    # Determine the current challenge number:
    # - Check whether the main page was modified.
    # - Update to the current challenge number if it has.
    # - If no change was detected, use what we have cached in status.toml.

    my $main_url = $status->{'main-url'};
    my $challenge_path = $status->{'current-challenge-path'};
    if ( page_was_modified( $main_url, 'main-last-modified' ) ) {
        my $xpath_pattern  = '\/blog\/perl-weekly-challenge-\\d+';
        $challenge_path = retrieve_challenge_link( $main_url, $xpath_pattern );
        %debug and dsay "challenge path: ", pp( $challenge_path );
        error_exit "could not extract challenge url, cannot continue"
            unless $challenge_path;

        if ( $challenge_path ne $status->{'current-challenge-path'}
	    || $options{FORCE} >= 3 )
	{
            ( $challenge ) = $challenge_path =~ /(\d+)$/;
            prot "New challenge $challenge detected."
                unless $options{QUIET};
            set_toml( $status, "current-challenge-path", $challenge_path );
            set_toml( $status, "current-challenge-last-modified", "" );
            set_toml( $status, "current-challenge-html-md5", "" );
        }
        else {
            vsay "challenge url has not changed";
        }
    }
    else {
        vsay "main page was not modified";
    }

    # Step 2:
    # Check the challenge page modification time.
    if ( page_was_modified(
        $main_url . $challenge_path, 'current-challenge-last-modified' ) )
    {
        vsay "challenge page was modified",
            $options{FORCE} ? " or reading is forced" : ();
        return $challenge;
    }
    elsif ( $options{FORCE} ) {
        vsay "challenge page was not modified, but reading is forced";
        return $challenge;
    }
    else {
        vsay "challenge page was not modified";
        return ();
    }
}

sub page_was_modified( $url, $last_modified_field_name ) {
    my @header = head( $url );
    my $modified_time = time_string( $header[2] );
    vsay "checking $url";
    vsay "    Last-Modified timestamp: ", pp( $modified_time );
    vsay "    we have:                 ",
        pp( $status->{$last_modified_field_name} ), ")";
    return 0
        if $status->{$last_modified_field_name}
            && $modified_time eq $status->{$last_modified_field_name};
    set_toml( $status, $last_modified_field_name, $modified_time );
    return 1;
}

use List::Util qw( all );

sub generate_code( $challenge, $task_text, $template, $tests ) {
    local $d_area = "code";
    %debug and dsay
        "generate_code( $challenge, ",
            "'", $task_text =~ /^(.*)?$/m, " [...]', ",
            "'", $template =~ /^(.*)?$/m, " [...]', ",
            "<tests> )";

    my ( $task, $task_name ) = $task_text =~ /^Task (\d+):\s*(.*?)\s*$/m;
    ( my $sub_name = lc $task_name ) =~ s/\W+/_/g;

    my $code = $template;

    my @checks = (
        [ "VARIABLE_NAMES", "input variable names" ],
        [ "INPUT",          "input data" ],
        [ "OUTPUT",         "expected output data" ],
    );
    for ( @checks ) {
        unless ( $tests->[0] && $tests->[0]{$_->[0]} ) {
            say STDERR "WARNING: ",
                "No $_->[1] were extracted for Task $task.";
        }
    }

    my @input_vars =
        $tests->[0] && $tests->[0]{VARIABLE_NAMES}
        ? @{$tests->[0]{VARIABLE_NAMES}}
        : ();
    my $json_input_vars = join ", ", map qq("$_"), @input_vars;

    # Turn array parameters into arrayrefs in some cases.
    if ( @input_vars > 1
        || $tests->[0] && $tests->[0]{INPUT}
            && ref $tests->[0]{INPUT}[0] eq 'ARRAY'
            && ref $tests->[0]{INPUT}[0][0] eq 'ARRAY' )
    {
        dsay "turning array parameter into arrayref";
        substr $_, 0, 1, '$'
            for @input_vars;
    }
    my $input_params = join ", ", @input_vars;

    my $result_var =
        $tests->[0] && ref $tests->[0]{OUTPUT} eq 'ARRAY'
        ? '@results'
        : '$result';

    my ( $single_input, $single_output ) =
        map {
            dsay "Checking single:";
            all { dsay "    ", pp $_; $_->@* == 1 && ! ref $_->[0] } $_->@*;
        }
        [ map $_->{INPUT},  $tests->@* ],
        [ map $_->{OUTPUT}, $tests->@* ];
    dsay "single input: ",  $single_input ? "yes" : "no";
    dsay "single output: ", $single_output ? "yes" : "no";

    my ( $single_arrayref_input, $single_arrayref_output ) = (
        $single_input  && ( all { ref $_->{INPUT}[0]  eq "ARRAY" } $tests->@* ),
        $single_output && ( all { ref $_->{OUTPUT}[0] eq "ARRAY" } $tests->@* ),
    );
    dsay "single arrayref input: ",  $single_arrayref_input  ? "yes" : "no";
    dsay "single arrayref output: ", $single_arrayref_output ? "yes" : "no";

    my $return =
        $tests->[0] && ref $tests->[0]{OUTPUT} eq 'ARRAY'
        ? ref $tests->[0]{OUTPUT}[0] eq 'ARRAY'
            ? '\@results'
            : '@results'
        : '$result';

    my $test_data = join "\n", 
        "my \@tests = (",
        ( map {
            my ( $name, $input, $expected ) = (
                pp( $_->{TEST} ),
                pp( $single_input ? $_->{INPUT}->[0] : $_->{INPUT} ),
                $single_output
                ? $_->{OUTPUT}[0] =~ /^(?:(t)rue|(f)alse)$/i
                    ? uc( $1 || $2 )
                    : pp( $_->{OUTPUT}->[0] )
                : pp( $_->{OUTPUT} )
            );
            my $line = "    [ $name, $input, $expected ],";
            $line = "    [ $name,\n        $input,\n        $expected ],"
                unless length( $line ) <= 80;
            $line;
        } $tests->@* ),
        ");";
    %debug and dsay $test_data;

    my $json_example_data = join ",\n",
        ( map {
            chomp ( my $entry = $templates->{json}{json_example} );
            my $indent = $templates->{json}{indent};
            my ( $name, $input, $output ) = (
                pp( $_->{TEST} ),
                pp( $_->{INPUT} ),
                $single_output && $_->{OUTPUT}[0] =~ /^(?:true|false)$/i
                    ? "[ $_->{OUTPUT}->[0] ]"
                    : pp( $_->{OUTPUT} )
            );
            for ( $input, $output ) {
                s/\n/\n$indent/g;
                s/,$(\n\s*\])/$1/msg;
            }
            my %substitutions = (
                NAME   => $name,
                INPUT  => $input,
                OUTPUT => $output,
            );
            $entry =~ s/<$_>/$substitutions{$_}/g
                for keys %substitutions;
            $entry;
        } $tests->@* );
    dsay ":json", "json example data:\n", $json_example_data;
    chomp( my $json = $templates->{json}{json} );
    $code =~ s/<JSON>/$json/;

    my $call = "$sub_name( \$_->[1]->\@* )";
    $call = "[ $call ]"
        unless $single_output;

    my %substitutions = (
        CHALLENGE    => $challenge,
        TASK_NUMBER  => $task,
        TASK_NAME    => $task_name,
        SUB_NAME     => $sub_name,
        INPUT_PARAMS => $input_params,
        RESULT_VAR   => $result_var,
        RETURN       => $return,
        TESTS        => $test_data,
        CALL         => $call,
        JSON_INPUT_VARS => $json_input_vars,
        JSON_EXAMPLE_DATA => $json_example_data,
    );
    $code =~ s/<$_>/$substitutions{$_}/g
        for keys %substitutions;

    %debug and dsay $code;
    return $code;
}

sub generate_readme_md( $challenge, $text ) {
    dsay ":readme", "text: ", pp $text;
    # Note that $text is pure text, no html.
    $text # =~ s/\r+//msr
          =~ /^ Task\s+1: \s* (?<t1_name>.*?) \s* $ \n
              ^ .*? Submitted .*? $ \n          # Skip 'Submitted' line.
              \s*? \n                           # Skip one empty line.
              (?<t1_text> ^\S.*? $              # Gather text from first
                                                # non-whitespace to eol,
                                                # not including \n.
                  (?: \n ^.*? $ )*?             # Gather continuation lines,
                                                # separated by \n.
              ) \n                              # Skip final \n.

              # Skip possible empty lines before 'Task 2'
              (?: ^\s*$ \n )*

              ^ Task\s+2: \s* (?<t2_name>.*?) \s* $ \n
              ^ .*? Submitted .*? $ \n
              \s*? \n
              (?<t2_text> ^\S.*? $
                  (?: \n ^.*? $ )*?
              ) \n

              # Skip possible empty lines before 'Last date ...' line
              (?: ^\s*$ \n )*

              ^ [^\n]* Last \s+ date [^\n]* \n
        /xmsi;
    my %parts = ( %+ );
    %debug and do {
        dsay ":readme", "$_: ", pp( $parts{$_} )
            for qw( t1_name t1_text t2_name t2_text );
    };

    for ( @parts{ qw( t1_text t2_text ) } ) {
	my ( $task_text, $examples ) = /\A(.*?)\n*(^Example 1.*)/ms;
	$task_text =~ s/\n/<br\/>\n/mg;
	$task_text .= "\n\n";
	$examples =~ s/\n+(Example \d+)/\n```\n\n$1/mg;
	$examples .= "\n```\n";
	$examples =~ s/^(Example \d+)\n/**$1**\n\n```text\n/mg;
	$_ = ( $task_text . $examples )
	    =~ s/^(.+)$/> $1/mgr
	    =~ s/^$/>/mgr;
    }

    my %substitutions = (
        CHALLENGE         => $challenge,
        TASK_1_NAME       => $parts{t1_name},
        TASK_1_Q_TEXT     => $parts{t1_text},
        TASK_2_NAME       => $parts{t2_name},
        TASK_2_Q_TEXT     => $parts{t2_text},
        TASK_1_SUB        => lc $parts{t1_name} =~ s/\W+/_/gr,
        TASK_2_SUB        => lc $parts{t2_name} =~ s/\W+/_/gr,
    );

    my $readme_text = $templates->{readme}{'readme_md'};
    # vsay $readme_text;
    $readme_text =~ s/<$_>/$substitutions{$_}/g
        for keys %substitutions;

    %debug && dsay ":readme", $readme_text;
    return $readme_text;
}

sub slurp_file( $file ) {
    open my $fh, "<", $file
        or error_exit "cannot open '$file': $!";
    my $text = do { local $/ = undef; <$fh> };
    close $fh;
    return $text;
}

sub spit_file( $file, $text ) {
    open my $fh, ">", $file
        or error_exit "cannot open '$file' for writing: $!";
    print $fh $text;
    close $fh;
}

sub time_string( $time ) {
    my $time_struct = localtime( $time );
    my $time_string = $time_struct->strftime( "%FT%T%z" );
    # Insert a ':' between the time zone hours and minutes to be RFC 3339
    # compatible (which is what TOML promotes), even if ISO allows time zones
    # without ':'. Actually with no real effect, since Perl TOML doesn't
    # convert datetime strings if no 'inflate_datetime' subroutine is given
    # to the TOML parser. So we will get the string back that we store.
    $time_string =~ s/(?=\d{2}$)/:/;
    return $time_string;
}

sub read_toml( $filename ) {
    my $toml_text = slurp_file( $filename );
    my $hash_ref = TOML::from_toml( $toml_text );
    # Keep the filename and the toml text for later writing back the file.
    @$hash_ref{ qw( TOML_FILE TOML_TEXT ) } = ( $filename, $toml_text );
    return $hash_ref;
}

sub write_toml( $hash_ref ) {
    my ( $filename, $toml_text ) = @$hash_ref{ qw( TOML_FILE TOML_TEXT ) };
    # Update the toml file if needed.
    spit_file( $filename, $toml_text )
        if $hash_ref->{TOML_CHANGED} && ! $options{DRY_RUN};
    delete $hash_ref->{TOML_CHANGED};
}

sub set_toml( $hash_ref, $name, $value ) {
    $hash_ref->{$name} = $value;
    $hash_ref->{TOML_TEXT} =~ s/^(\s* ${name} \s* = \s* ).*?$/${1}"${value}"/xm;
    $hash_ref->{TOML_CHANGED} = 1;
}

sub timestamp {
    return localtime->strftime( "%y%m%d_%H%M%S" );
}

1;
