#!/bin/bash
#
#	install - copy current implementation to .../weekly_check.
#

files="
    TestExtractor.pm
    download_challenge
    templates.toml
    download_challenge.crontab
"

target_dir="../weekly_check"

mkdir -p "$target_dir"
for f in $files; do
    if ! cmp --quiet "$f" "$target_dir/$f"; then
	echo "copying $f to $target_dir"
	cp -p "$f" "$target_dir/$f"
    fi
done
