#
#   status.toml
#
main-url = "https://theweeklychallenge.org"
main-last-modified = "2023-05-30T12:00:22+02:00"

current-challenge-path = "/blog/perl-weekly-challenge-219"
current-challenge-last-modified = "2023-05-30T12:00:22+02:00"
current-challenge-html-md5 = "6189bec2083ffce4b787e5026890fa96"

user = "matthias-muth"
recipients = [ "muthm@gmx.de" ]
