#
#   status.toml
#
main-url = "https://theweeklychallenge.org"
main-last-modified = "2023-05-15T02:55:51+02:00"
challenge-path = "/blog/perl-weekly-challenge-216"
challenge-last-modified = "2023-05-15T02:55:50+02:00"
challenge-html-md5 = "69bd0fe07d0428af6261b3cad046f9e0"
user = "matthias-muth"
recipients = [ "muthm@gmx.de" ]
