#
#   status.toml
#
main-url = "https://theweeklychallenge.org"
main-last-modified = "2023-10-02T09:23:49+02:00"

current-challenge-path = "/blog/perl-weekly-challenge-237"
current-challenge-last-modified = "2023-10-02T09:23:49+02:00"
current-challenge-html-md5 = "c541b7432ddf211e701b4ca6d3a95718"

user = "matthias-muth"
recipients = [ "muthm@gmx.de" ]
