#
#   status.toml
#
main-url = "https://theweeklychallenge.org"
main-last-modified = "2024-02-13T14:16:21+01:00"

current-challenge-path = "/blog/perl-weekly-challenge-256"
current-challenge-last-modified = "2024-02-13T14:16:22+01:00"
current-challenge-html-md5 = "cd31556b4a7734ccea297eae6d153c6e"

user = "matthias-muth"
recipients = [ "muthm@gmx.de" ]
