#
#   template.toml
#

[ mail ]

html = '''
<!DOCTYPE html>
<html class="no-js" lang="en-us">
<head>
    <!-- Basic Page Needs -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <!-- Mobile Specific Metas -->
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>The Weekly Challenge - <CHALLENGE></title>
    <link rel="icon" href="https://theweeklychallenge.org/images/favicon.ico">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"/>

    <!-- template main css file -->
    <link rel="stylesheet" href="https://theweeklychallenge.org/css/style.min.css" integrity="" media="screen">
</head>

<body>
<PAGE_HEADER>
<section class="single-post">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div style="text-align: justify" class="post-content">
<TASKS>
</body>
</html>
'''

[code]

ch-N_pl = '''
#!/usr/bin/env perl
#
#       The Weekly Challenge - Perl & Raku
#       (https://theweeklychallenge.org)
#
#       Challenge <CHALLENGE> Task <TASK_NUMBER>: <TASK_NAME>
#
#       Perl solution by Matthias Muth.
#

use strict;
use warnings;
use feature 'say';

use lib '.';
use TestExtractor;

use List::Util qw( sum min max );

sub <SUB_NAME> {
    my ( <INPUT_PARAMS> ) = @_;

    my <RESULT_VAR>;

    return <RETURN>;
}

run_tests;
'''
