#!/usr/bin/env perl
#
#       update_gists
#
#   Intended usage:
#       update_gists
#               check for changes,
#               process unprocessed gists
#               optionally commit into dev
#               optionally commit into muthm
#               optionally create pull request
#               mark as processed if everything succeeded.
#       update_gist <challenge> TODO
#               unconditionally get the gist
#                       (may require looking up in the list of gists,
#                       then downloading the gist)

use v5.36;

use Verbose;
use Dsay;

use Getopt::Long;
use HTTP::Tiny;
use JSON qw(decode_json);
use TOML;
use Time::Piece;
use List::UtilsBy qw( nsort_by );
use Dsay;

GetOptions(
    "check|n"    => \$options{DRY_RUN},
) or do {
    say STDERR "    Use '$0 -help' for usage information.";
    exit 2;
};

# Read the status TOML file for the last timestamp.
# Read 'status.toml' and keep the status as global variables.
our $status   = read_toml( "status.toml" );

my $last_checked = $status->{'gists-last-checked'};
my $start_time = localtime;

# Get list of gists from github.
my $ua = HTTP::Tiny->new;
my $r = $ua->get(
    "https://api.github.com/users/manwar/gists?since=$last_checked"
);
my $gists = decode_json($r->{content});

# dsay "gists: ", pp $gists;

for my $gist ( nsort_by { $_->{'description'} =~ /(\d+)/; $1 } @$gists ) {
    vsay "$gist->{id} $gist->{description}\n",
        "    created $gist->{created_at}\n",
        "    updated $gist->{updated_at}";
    dsay ":info", "    $_: ", $gist->{$_} // "(undef)"
        for sort keys %$gist;

    # Get the gists challenge number and html text.
    ( my $challenge ) = $gist->{description} =~ /(\d+)/;

    # Skip if this challenge was published already.
    $challenge > $status->{'challenge-number'} or do {
        vsay "challenge $challenge is published already, skipping";
        next;
    };

    my $page = $ua->get( $gist->{url} );
    my $gist_data = decode_json($page->{content});
    my $gist_page = $ua->get( $gist_data->{html_url} );
    my $text = $gist_page->{content};

    # Process the gist, producing local files.
    my @download_command = (
        qw( download_challenge --no-mail --no-git -debug on -i - ),
        $options{DRY_RUN} ? "-n" : (),
        $verbose ? "-v" : (),
    );
    open my $download_process, "|-", @download_command
        or die "could not open pipe to '@download_command': $!\n";
    print $download_process $text;
    close $download_process;

    # Add the new files to Git.
    system "git add ../challenge-$challenge/examples";
    system qw( git commit -uno -m ),
        "Add JSON test data and Perl solution templates"
            . " for Challenge $challenge";
    system qw( ../publish.pl -json ), $challenge;
}

my $timestamp = $start_time->strftime( "%FT%T%z" );
substr( $timestamp, -2, 0 ) = ":";
set_toml( $status, 'gists-last-checked', $timestamp );

# Update the status toml file.
write_toml( $status );

exit 0;

sub error_exit { say STDERR $0 =~ s'^.*/''r, ": ", @_; exit 1 }

sub slurp_file( $file ) {
    open my $fh, "<", $file
        or error_exit "cannot open '$file': $!";
    my $text = do { local $/ = undef; <$fh> };
    close $fh;
    return $text;
}

sub spit_file( $file, $text ) {
    open my $fh, ">", $file
        or error_exit "cannot open '$file' for writing: $!";
    print $fh $text;
    close $fh;
}

sub read_toml( $filename ) {
    my $toml_text = slurp_file( $filename );
    my $hash_ref = TOML::from_toml( $toml_text );
    # Keep the filename and the toml text for later writing back the file.
    @$hash_ref{ qw( TOML_FILE TOML_TEXT ) } = ( $filename, $toml_text );
    return $hash_ref;
}

sub write_toml( $hash_ref ) {
    my ( $filename, $toml_text ) = @$hash_ref{ qw( TOML_FILE TOML_TEXT ) };
    # Update the toml file if needed.
    spit_file( $filename, $toml_text )
        if $hash_ref->{TOML_CHANGED} && ! $options{DRY_RUN};
    delete $hash_ref->{TOML_CHANGED};
}

sub set_toml( $hash_ref, $name, $value ) {
    $hash_ref->{$name} = $value;
    $hash_ref->{TOML_TEXT} =~ s/^(\s* ${name} \s* = \s* ).*?$/${1}"${value}"/xm;
    $hash_ref->{TOML_CHANGED} = 1;
}
