name = "ch_1"
description = ""
version = "0.1.0-dev"

authors = ["BarrOff"]
maintainers = ["BarrOff <example@example.com>"]
maintainers-logins = ["BarrOff"]
licenses = "BSD-3-Clause"
website = ""
tags = []

executables = ["ch_1"]
