# SPDX-FileCopyrightText: Peter Pentchev <roam@ringlet.net>
# SPDX-License-Identifier: BSD-2-Clause

version = 1
SPDX-PackageName = "pwc-312"
SPDX-PackageSupplier = "Peter Pentchev <roam@ringlet.net>"
SPDX-PackageDownloadLocation = "https://git@github.com/ppentchev/perlweeklychallenge-club"

[[annotations]]
path = [
  "uv.lock",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Peter Pentchev <roam@ringlet.net>"
SPDX-License-Identifier = "BSD-2-Clause"
