#!/usr/bin/env perl

use v5.36;

my ( $commenting, $indent, @words );

while ( <> ) {
    # Expand tabs.
    while( /\t/ ) {
	my $n_spaces = 8 - $_[0] % 8;
	substr( $_, $-[0], 1 ) = " " x $n_spaces;
    }

    s/^(\s*\#)//;
    $commenting //= $1;
    
    next if /^\s*$/;

    s/^(\s*)/
    $indent //= $1;

    push @text, split " ", $';
}

