# SPDX-FileCopyrightText: Peter Pentchev <roam@ringlet.net>
# SPDX-License-Identifier: BSD-2-Clause

name: pwc_312
description: "Peter Pentchev's solutions to the Perl Weekly Challenge 312"

version: 0.1.0

environment:
    sdk: ^3.0.0

dependencies:
    characters: ^1.4.0

dev_dependencies:
    test: ^1.25.2
