# SPDX-FileCopyrightText: Peter Pentchev <roam@ringlet.net>
# SPDX-License-Identifier: BSD-2-Clause

version = 1
SPDX-PackageName = "pwc-293-ppentchev"
SPDX-PackageSupplier = "Peter Pentchev <roam@ringlet.net>"
SPDX-PackageDownloadLocation = "https://devel.ringlet.net/misc/perlweeklychallenge-club"

[[annotations]]
path = "rust/Cargo.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "Peter Pentchev <roam@ringlet.net>"
SPDX-License-Identifier = "BSD-2-Clause"
