# SPDX-FileCopyrightText: Peter Pentchev <roam@ringlet.net>
# SPDX-License-Identifier: BSD-2-Clause

version = 1
SPDX-PackageName = "pwc-289-ppentchev"
SPDX-PackageSupplier = "Peter Pentchev <roam@ringlet.net>"
SPDX-PackageDownloadLocation = "https://devel.ringlet.net/{{ website_section }}/{{ name }}/"

[[annotations]]
path = "rust/Cargo.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "Peter Pentchev <roam@ringlet.net>"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = "test-data/jumbled-letters/*.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "Peter Pentchev <roam@ringlet.net>"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = "test-data/jumbled-letters/*.txt.sorted"
precedence = "aggregate"
SPDX-FileCopyrightText = "Peter Pentchev <roam@ringlet.net>"
SPDX-License-Identifier = "BSD-2-Clause"
