[package]
name = "find_third"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "Weekly challenge 315 task 2 - find words following the specified two"
authors = ["Peter Pentchev <roam@ringlet.net>"]
license = "BSD-2-Clause"
